package ru.nix13.asakusa

import cpw.mods.fml.common.Mod
import cpw.mods.fml.common.ModMetadata
import cpw.mods.fml.common.event.FMLInitializationEvent
import cpw.mods.fml.common.event.FMLPreInitializationEvent
import cpw.mods.fml.common.eventhandler.SubscribeEvent
import net.minecraft.client.Minecraft
import net.minecraft.entity.player.EntityPlayer
import net.minecraft.event.ClickEvent
import net.minecraft.util.ChatComponentText
import net.minecraft.util.ChatComponentTranslation
import net.minecraft.util.EnumChatFormatting
import net.minecraft.util.StatCollector
import net.minecraftforge.common.ForgeHooks
import net.minecraftforge.common.MinecraftForge
import net.minecraftforge.event.entity.EntityJoinWorldEvent
import net.minecraftforge.event.world.WorldEvent
import ru.nix13.asakusa.utils.UpdateChecker

@Mod(modid = AsakusaLib.modId, name = AsakusaLib.name, version = AsakusaLib.version)
class AsakusaLib {
    companion object {
        const val modId = "asakusa-lib"
        const val name = "Asakusa Lib"
        const val version = "1.0.0"
        const val updateUrl = "https://nix13.pw/asakusa_lib.json"
    }

    @Mod.EventHandler
    fun preInit(e: FMLPreInitializationEvent) {
        modMetadata(e.modMetadata)
    }

    @Mod.EventHandler
    fun init(e: FMLInitializationEvent) {
        MinecraftForge.EVENT_BUS.register(this)
    }

    @SubscribeEvent
    fun onPlayerLogged(e: EntityJoinWorldEvent) {
        if(!e.world.isRemote) return
        if(e.entity !is EntityPlayer) return
        val info = UpdateChecker.checkForUpdates(updateUrl) ?: return
        if(info.modVersionRecommended == version) return

        val player = e.entity as EntityPlayer
        val text = ChatComponentText(
            "[${EnumChatFormatting.GREEN}Asakusa${EnumChatFormatting.RESET}] ${StatCollector.translateToLocal("ru.nix13.asakusa.update")}: ${EnumChatFormatting.AQUA}${info.modVersionRecommended}"
        )
        player.addChatComponentMessage(text)
        player.addChatComponentMessage(ChatComponentText(StatCollector.translateToLocal("ru.nix13.asakusa.update_get")))
        player.addChatComponentMessage(ForgeHooks.newChatWithLinks(info.homepage))
    }

    private fun modMetadata(meta: ModMetadata) {
        meta.autogenerated = false
        meta.modId = modId
        meta.version = version
        meta.name = name
        meta.url = "https://www.curseforge.com/minecraft/mc-mods/asakusalib"
        val authorList = meta.authorList
        authorList.add("Nix13")
    }
}